services:
  counter-api:
    build: .
    container_name: counter-api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - RATE_LIMIT_WINDOW=60000
      - RATE_LIMIT_MAX_REQUESTS=100
      - PORT=3000
    ports:
      - '3000:3000'
    volumes:
      - ./data:/app/data:rw
    # Health check configuration - optimized for fast startup
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "const port=process.env.PORT||3000;require('http').get('http://localhost:'+port+'/health',(r)=>process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))",
        ]
      interval: 15s
      timeout: 5s
      start_period: 15s
      retries: 3
    # For direct access without Traefik, uncomment the line below:
    # networks: []
    networks:
      - web
    # Security hardening
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=100m
    labels:
      - 'traefik.enable=true'
      # HTTP to HTTPS redirect
      - 'traefik.http.routers.api.rule=Host(`${API_DOMAIN:-api.localhost}`)'
      - 'traefik.http.routers.api.entrypoints=web'
      # Temporarily disable HTTPS redirect for debugging
      # - 'traefik.http.routers.api.middlewares=api-https-redirect'
      # - 'traefik.http.middlewares.api-https-redirect.redirectscheme.scheme=https'
      # HTTPS with security headers
      - 'traefik.http.routers.api-secure.rule=Host(`${API_DOMAIN:-api.localhost}`)'
      - 'traefik.http.routers.api-secure.entrypoints=websecure'
      - 'traefik.http.routers.api-secure.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.api-secure.middlewares=api-security-headers'
      - 'traefik.http.services.api.loadbalancer.server.port=3000'
      # Security headers middleware
      - 'traefik.http.middlewares.api-security-headers.headers.customrequestheaders.X-Forwarded-Proto=https'
      - 'traefik.http.middlewares.api-security-headers.headers.sslredirect=true'
      - 'traefik.http.middlewares.api-security-headers.headers.stsincludesubdomains=true'
      - 'traefik.http.middlewares.api-security-headers.headers.stspreload=true'
      - 'traefik.http.middlewares.api-security-headers.headers.stsseconds=31536000'
      - 'traefik.http.middlewares.api-security-headers.headers.framedeny=true'
      - 'traefik.http.middlewares.api-security-headers.headers.contentTypeNosniff=true'
      - 'traefik.http.middlewares.api-security-headers.headers.browserXssFilter=true'
      - 'traefik.http.middlewares.api-security-headers.headers.referrerPolicy=strict-origin-when-cross-origin'

networks:
  web:
    external: true
